config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  devise_for :users
  resources :contacts, only: [:new, :create]
  resources :posts

  root 'landing#index'

  match '/myposts', to: 'posts#myposts', via: :get
  match '/calendar', to: 'landing#calendar', via: :get  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

   # Declare the e-mail headers. It accepts anything the mail method
   # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "umdmasterpiece@gmail.com",
      :from => %("#{name}" <#{email}>)
     }
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end 
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

  def calendar
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
    before_action :find_post, only: [:edit, :update, :show, :delete]
    before_action :authenticate_user!, except: [:index, :show]
  
    # Index action to render all posts
    def index
      @posts = Post.where(params[:id]).order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    end
  
    # New action creates the posts
    def new
      @post = Post.new
    end
  
    # Saves the post into database
    def create
      @post = Post.new(post_params)
      @post.user = current_user
      if @post.save
        flash.now[:notice] = "Successfully created post!"
        redirect_to post_path(@post)
      else
        flash.now[:alert] = "Error creating new post!"
        render :new
      end
    end
  
    def edit
    end
  
    def update 
      if @post.update_attributes(post_params)
        flash.now[:notice] = "Successfully updated post!"
        redirect_to post_path(@posts)
      else 
        flash[:alert] = "Error updating post!"
        render :edit 
      end 
    end
  
    def show
    end
  
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to myposts_path
    end

    def myposts
      @post = Post.where(user: current_user)
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :body, :description, :image)
    end
  
    def find_post 
      @post = Post.find(params[:id])
    end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :check_authorization, only: [:edit, :update]
  before_action :set_user

  def initialize
    
  end

  def show
  end 

  def index 
  end 

  def edit
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:id])
    if @user.save
      flash.now[:success] = "Successfully registered"
      redirect_to root_path
    else
      flash.now[:error] = "Cannot create a user, try again"
    end 
  end

  def update
    if @user.update(params[:id])
      redirect_to @user 
    else 
      flash.now[:alert] = "Something went wrong"
      render :edit
    end
  end

  private

    def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog_posts/_form.html.erb
<%= simple_form_for @blog_post do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@blog_post.errors.count, "error")} prohibited this post from being saved: " %>
      </h2>
      <ul>
        <% @blog_post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-control">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, as: :bootsy %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h2>Create A New Blog Post</h2>

<%= render 'blog_posts/form' %>

app/views/contacts/create.html.erb
<h1 class="page_title">Contact Us</h1>

<div class="skinny_wrapper wrapper_padding">
    <h1>Thank you for your message!</h1>
      <p>We will get back to you soon</p>
</div>

app/views/contacts/new.html.erb
<h1 class="text-center mast-title">CONTACT US</h1>
<br />
<br />
<div class="container">
  <div class="row">
    <%= form_for @contact do |f| %>
    
      <!-- Name -->
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :name,  required: true, class: 'form-control', id: 'Name', placeholder: 'Name' %>
          </div>
        </div>
        <!-- Email -->
        <div class="col-md-6">
          <div class="form-group">
            <%= f.email_field :email,  required: true, class: 'form-control', id: 'email', placeholder: 'E-mail' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= f.text_area :message, as: :text, placeholder: 'Message', rows: '9', class: 'form-control textarea', id: 'Message' %>
          </div>
        </div>
      </div>

      <!-- Submit button -->
      <div class="row">
        <div class="col-md-12">
          <%= f.submit 'Send', class: 'btn main-btn pull-right' %>
        </div>
      </div>

      <!-- Hidden -->
      <div class="hidden form-group">
        <%= f.label :nickname %>
        <div class="col-md-9">
          <%= f.text_field :nickname, hint: 'leave this field blank', class: 'form-control' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/landing/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
    <li data-target="#myCarousel" data-slide-to="7"></li>
    <li data-target="#myCarousel" data-slide-to="8"></li>
    <li data-target="#myCarousel" data-slide-to="9"></li>
    <li data-target="#myCarousel" data-slide-to="10"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("group_pic_3.jpg", class: 'first-slide') %>
    </div>
    <div class="item">
      <%= image_tag("group_pic_2.jpg", class: 'second-slide') %>
    </div>
    <div class="item">
        <%= image_tag("group_pic_1.jpg", class: 'third-slide') %>
    </div>
    <div class="item">
        <%= image_tag("group_pic_4.jpg", class: 'fourth-slide') %>
    </div>
    <div class="item">
      <%= image_tag("line.jpg", class: 'fifth-slide') %>
    </div>
    <div class="item">
      <%= image_tag("hug.jpg", class: 'sixth-slide') %>
    </div>
    <div class="item">
      <%= image_tag("laugh.jpg", class: 'seventh-slide') %>
    </div>
    <div class="item">
      <%= image_tag("group.jpg", class: 'eigth-slide') %>
    </div>
    <div class="item">
      <%= image_tag("oa.jpg", class: 'ninth-slide') %>
    </div>
    <div class="item">
      <%= image_tag("wall.jpg", class: 'tenth-slide') %>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/landing/calendar.html.erb
<!-- Calendar goes here -->
<div>
  <h2 class="mast-title">MasTERPiece Calendar</h2>
  <div class="mast-title">
    <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;height=400&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=hd6cditpgq3npgslh8mpar7e60%40group.calendar.google.com&amp;color=%23691426&amp;ctz=America%2FNew_York" style="border-width:0" width="700" height="400" frameborder="0" scrolling="no"></iframe>
  </div>
</div>

app/views/landing/index.html.erb
<body>
  <main>
    <!--<div class="group-pic">
      <div class="caption">
        <button class="border btn btn-default btn-outline btn-circle"><%= link_to "CONTACT US", new_contact_path %></button>
      </div>
    </div>-->
    <%= render "landing/carousel" %>
  </main>
  <div class="row">
    <div class="about container ">
        <!--<iframe src="https://calendar.google.com/calendar/embed?height=300&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=kwesiiilarb%40gmail.com&amp;color=%2329527A&amp;ctz=America%2FNew_York" style="border:solid 1px #777" width="500" height="300" frameborder="0" scrolling="no"></iframe>-->
      <div class="sec-about">
        <h3 class="label-about mast-title">About</h3>
          <p class="about-description">
            MasTERPiece seeks to create and serve a community of those interested in the fashion/retail industry through our general gody meetings, professional development, community service and UMD Fashion Week.
          </p>
        </div>
      </div>
    </div>
    <div>
      <div class="pic12"></div>
    </div>
    <div class="container sec-about">
      <div class="at-section">
        <div class="mast-title label-about">EBoard</div>
      </div>
      <div class="at-grid sec-about container" data-column="3">
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic7.jpg") %></div>
            <div class="at-user__name">Oru Wonodi</div>
            <div class="at-user__title">President</div>
            <ul class="at-social">
              <li class="at-social__item">
                  <a href="https://twitter.com/obiwanwonodi?lang=en" target="_blank">
                    <i class="fa fa-twitter fa-social" aria-hidden="true"></i>
                  </a>
              </li>
        
              <li class="at-social__item">
                <a href="https://www.instagram.com/obiwanwonodi/" target="_blank">
                  <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic2.jpg") %></div>
            <div class="at-user__name">Saron Bizuayehu</div>
            <div class="at-user__title">Vice President</div>
            <ul class="at-social">
              <li class="at-social__item">
                <a href="https://www.instagram.com/_saronnn/" target="_blank">
                  <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic3.jpg") %></div>
            <div class="at-user__name">LaRen Morton</div>
            <div class="at-user__title">VP of Public Relations</div>
            <ul class="at-social">
              <li class="at-social__item">
                <a href="https://twitter.com/xoxo_lbm?lang=en" target="_blank">
                  <i class="fa fa-twitter fa-social" aria-hidden="true"></i>
                </a>
              </li>
            
              <li class="at-social__item">
                <a href="https://www.instagram.com/xolarenbrie/" target="_blank">
                  <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic5.jpg") %></div>
            <div class="at-user__name">Julia Stratford</div>
            <div class="at-user__title">VP of Finance</div>
            <ul class="at-social">
                <li class="at-social__item">
                  <a href="https://twitter.com/laurenlillie" target="_blank">
                    <i class="fa fa-twitter fa-social" aria-hidden="true"></i>
                  </a>
                </li>
                  
                <li class="at-social__item">
                  <a href="https://www.instagram.com/laurenhmacp/" target="_blank">
                    <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                  </a>
                </li>
              </ul>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic4.jpg") %></div>
            <div class="at-user__name">Lauren Allen</div>
            <div class="at-user__title">Community Service Chair</div>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic8.jpg") %></div>
            <div class="at-user__name">Justin Nwosu</div>
            <div class="at-user__title">PR Chair</div>
          </div>
        </div>
        <div class="at-column">
          <div class="at-user">
            <div class="at-user__avatar"><%= image_tag("pic6.jpg") %></div>
            <div class="at-user__name">Lidija Jurovich</div>
            <div class="at-user__title">VP of Marketing</div>
              <ul class="at-social"> 
                <li class="at-social__item">
                  <a href="https://www.instagram.com/lidijajurovich/?hl=en" target="_blank">
                    <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="at-column">
            <div class="at-user">
              <div class="at-user__avatar"><%= image_tag("pic9.jpg") %></div>
              <div class="at-user__name">Nia Parks</div>
              <div class="at-user__title">VP of Events</div>
              <ul class="at-social">
                <li class="at-social__item">
                  <a href="https://www.instagram.com/ni_parks/" target="_blank">
                    <i class="fa fa-instagram fa-social" aria-hidden="true"></i> 
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="at-column">
            <div class="at-user">
              <div class="at-user__avatar"><%= image_tag("pic10.jpg") %></div>
              <div class="at-user__name">Samuel Barksdale</div>
              <div class="at-user__title">Finance Chair</div>
            </div>
          </div>
          <div class="at-column">
            <div class="at-user">
              <div class="at-user__avatar"><%= image_tag("pic11.jpg") %></div>
              <div class="at-user__name">Dimitry Decolin</div>
              <div class="at-user__title">Secretary</div>
              <ul class="at-social">
                <li class="at-social__item">
                  <a href="https://twitter.com/ddecolin?lang=eu" target="_blank">
                    <i class="fa fa-twitter fa-social" aria-hidden="true"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </div>
      <div class="blog-div">
        <div class="blog">
          <span><%= link_to "Check out our blog!!", posts_path, :style => 'color: #fff;' %></span>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/landing/show.html.erb
<h1>Hello World</h1>

app/views/layouts/_disqus.html.erb
<div id="disqus_thread"></div>
<script id="dsq-count-scr" src="//umdmasterpiece-1.disqus.com/count.js" async></script>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = "<%= url_for([@post, {only_path: false}]) %>";  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = "<%= @post.title %>"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};*/

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://umdmasterpiece-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            
                            

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <ul class="pull-left footer-logo">
      <li><%= image_tag("Masterpiece_Logo_Symbol.png", size: 44, class: 'logo') %></li>
    </ul>
    <ul class="social-icon animate pull-right">
      <li>
        <a href="https://www.facebook.com/umdmasterpiece/" title="facebook" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
      </li> 
      <li>
        <a href="https://twitter.com/umdmasterpiece" title="twitter" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a>
      </li>
      <li>
        <a href="https://www.instagram.com/umdmasterpiece/" class="instagram" target="_blank"><i class="fa fa-instagram"></i></a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!--<div style="background-color: rgb(249, 247, 247);">
		<nav class="navbar navbar-default tembus">
		  <div class="container">
		    <div class="navbar-header">
          <%= link_to image_tag("logo.png", size: 40, class: 'logo button-left left-side'), root_path %>
				</div>			
		    <div class="drops collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to 'Blog', posts_path, class: 'hvrcenter navtext' %></li>
            <li><%= link_to 'Contact Us', new_contact_path, class: 'hvrcenter navtext' %></li>
						<% if user_signed_in? %>
							<li>
								<div class="btn-group show-on-hover">
									<i class="fa fa-bars" aria-hidden="true"></i>										
									<ul class="dropdown-menu" role="menu">
										<li class="nav-item">
											<%= link_to 'My Posts', myposts_path %>
										</li>
										<li class="nav-item">
											<%= link_to 'New Post', new_post_path %>
										</li>
										<li class="nav-item">
											<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
										</li>	
									</ul>
								</div>
							</li>
						<% end %>
		      </ul>
		    </div>
		  </div>
		</nav>
</div>-->
<header role="banner">
	<nav id="navbar-primary" class="navbar" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-primary-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="navbar-primary-collapse">
				<ul class="nav navbar-nav">
					<li class="menu-items active">
						<%= link_to 'Home', root_path %>
					</li>

					<li class="menu-items">
						<%= link_to 'Blog', posts_path, class: 'hvrcenter navtext' %>
					</li>

					<% if user_signed_in? %>
						<li class="menu-items">
							<%= link_to 'My Posts', myposts_path %>
						</li>
					<% end %>

					<li>
						<%= image_tag("Masterpiece_Logo_Full .png", width:"250", class: ' button-left left-side') %>
					</li>

					<% if user_signed_in? %>
						<li class="menu-items">
							<%= link_to 'New Post', new_post_path %>
						</li>
					<% end %>

					<li class="menu-items">
						<%= link_to 'Contact', new_contact_path, class: 'hvrcenter navtext' %>
					</li>

					<li class="menu-items">
						<%= link_to 'Calendar', calendar_path %>
					</li>
				</ul>

				<% if user_signed_in? %>
					<ul class="log-nav">
						<li class="menu-items">
							<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
						</li>	
					</ul>
				<% end %>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UMDMasTERPiece</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Permanent+Marker');
    </style>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>  
  </head>

  <body>
    <%= slide_down_alerts %>
    
    <%= render 'layouts/navbar' %>

    <%= yield %>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved: " %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <div class="">
      <%= f.label :title %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <br />
  
    <div class="">
      <%= f.label :description %><br />
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    
    <br />
    
    <div class="form-group">
      <%= f.label "Upload Image" %>
      <%= f.file_field :image %>
        <!--<%= f.label :banner_image_url%>
        <%= f.text_field :banner_image_url, class: 'form-control' %>-->
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <%= f.input :body %>
    </div>
  
    <div class="form-group">
      <%= f.button :submit %>
    </div>
  </div>

 

<% end %>

app/views/posts/_post.html.erb
<tr>
    <td><%= post.title %></td>
  
    <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %></td>
    <td><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
</tr>

app/views/posts/edit.html.erb
<div class="container">
  <h2 class="mast-title" style="text-align: center;">Edit Blog Post</h2>
  <%= render 'posts/form' %>
</div>

app/views/posts/index.html.erb
<div class="row">
    <section>
        <div class="latest-news-box">
          <div class="row nomargin">
              <% @posts.each do |post| %>
              <div class="col-md-6 nopadding">
                <div class="item item-left">
                  <div class="col-md-6 nopadding hidden-xs">
                    <%= image_tag post.image.url(:large) %>
                    <span class="image-overflow"></span>
                    <div class="arrow-left"></div>
                  </div>
                  <div class="col-md-6 nopadding">
                    <div class="content">
                      <h2><%= link_to post.title, post %></h2>
                      <p><%= truncate(post.description, length: 130) %></p>
                      <%= link_to 'See More...', post, class: 'btn btn-primary' %>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
            <div class="paginate">
              <%= will_paginate @posts, previous_label: "Newer", next_label: "Older", inner_window: 2, outer_window: 0, renderer: BootstrapPagination::Rails %>   
            </div>
        </div>
      </section>
</div>

app/views/posts/myposts.html.erb
<h1 class="mast-title">My Posts</h1>
<div class="container">
  <div class="row">
    <section class="content">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="table-container">
              <div id="new_listing_button">
                <%= link_to 'New Post', new_post_path, class: "btn btn-info" %>
              </div>
              <br />
              <table class="table table-filter">
                <tr>
                  <th class="mylistings-title" colspan="5">Title</th>
                </tr>
                <%= render @post %>
              </table>
              <br />
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="mast-title" style="text-align: center;">Create A New Blog Post</h2>
  
  <%= render 'posts/form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <div class="content">
        <h1 class="mast-title disqus"><%= @post.title %></h1>
        <% if user_signed_in? %>
          <div class="edit-btn">
            <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-sm btn-warning'%>
            <%= link_to 'Remove', post_path(@post), method: :delete,
                    data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'%>
          </div>
        <% end %>
        <div class="disqus">
          <%= @post.body.html_safe %>
        </div>
        <!-- Populate tags here -->
        <div class="col-md-12 disqus">
          <%= render "layouts/disqus" %>
        </div>
      </div>
    </div>
  </div>
</div>